### ISSUE TITLE
overflows 4em

### ISSUE THREAD

**Issue by Haroenv** [bullgit/chitchat#6]
```css
message {
float: left;
width: 100%;
height: auto;
border-top: 1px solid #eff0f2;
border-bottom: 1px solid #eff0f2;
line-height: 1;
position: relative;
margin-top: 8px;
left: -2em;
}
```

In `style.css:196`, but if you leave out the `position: relative` it fixes the weird overflow, but it also gives it a height that's too much
